-- Migration 002: Add expanded ATS metrics to proxy_stats
ALTER TABLE proxy_stats ADD COLUMN IF NOT EXISTS total_requests BIGINT DEFAULT 0;
ALTER TABLE proxy_stats ADD COLUMN IF NOT EXISTS connect_requests BIGINT DEFAULT 0;
ALTER TABLE proxy_stats ADD COLUMN IF NOT EXISTS responses_2xx BIGINT DEFAULT 0;
ALTER TABLE proxy_stats ADD COLUMN IF NOT EXISTS responses_3xx BIGINT DEFAULT 0;
ALTER TABLE proxy_stats ADD COLUMN IF NOT EXISTS responses_4xx BIGINT DEFAULT 0;
ALTER TABLE proxy_stats ADD COLUMN IF NOT EXISTS responses_5xx BIGINT DEFAULT 0;
ALTER TABLE proxy_stats ADD COLUMN IF NOT EXISTS err_connect_fail INTEGER DEFAULT 0;
ALTER TABLE proxy_stats ADD COLUMN IF NOT EXISTS err_client_abort INTEGER DEFAULT 0;
ALTER TABLE proxy_stats ADD COLUMN IF NOT EXISTS broken_server_conns INTEGER DEFAULT 0;
ALTER TABLE proxy_stats ADD COLUMN IF NOT EXISTS bytes_in BIGINT DEFAULT 0;
ALTER TABLE proxy_stats ADD COLUMN IF NOT EXISTS bytes_out BIGINT DEFAULT 0;
